version: '2.30.3'

services:
  db:
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: 'postgres:17-alpine'
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb